### ISSUE TITLE
Google Account setting problem. 

### ISSUE THREAD

**Issue by ParkJaeSeong** [ntawileh/obsidian-google-lookup#7] opened 2022-06-25 11:44 UTC
I had set up the Google Cloud project. But when I add google account, my account is not added. I don't know the problem by looking at the log in console. I need help.

![image](https://user-images.githubusercontent.com/9565700/175771911-32e855ab-b822-4147-8639-837fbcaeab3f.png)

![image](https://user-images.githubusercontent.com/9565700/175771922-cf65b606-9d67-4a95-b812-ffe738b17725.png)

![image](https://user-images.githubusercontent.com/9565700/175771951-884e1618-7280-4e96-84a4-db4e526e1f77.png)

![image](https://user-images.githubusercontent.com/9565700/175771959-d04ba0e7-e925-4b72-b279-3c22cc0433db.png)

![image](https://user-images.githubusercontent.com/9565700/175772022-ad3e969e-05e5-41be-9e4e-15e3c0e2d05d.png)

![image](https://user-images.githubusercontent.com/9565700/175772032-fb7032b4-0f34-434d-9740-0f40744f2867.png)

**Comment by ntawileh** [comment] 2022-06-25 18:55
just going by the console output, it seems the query to fetch your own email address is not returning anything.  
* when you were prompted with the oauth login for the app, did you make sure to check every box in order to give permissions to all required scopes?
* one thing that could help also is going [here](https://developers.google.com/people/api/rest/v1/people/get?apix_params=%7B%22resourceName%22%3A%22people%2Fme%22%2C%22personFields%22%3A%22names%2Cnicknames%2CemailAddresses%22%7D) and hit the Execute button on the right.  This does the same query against your account.  If successful, paste in the response here

**Comment by ParkJaeSeong** [comment] 2022-06-26 06:48
Thanks you ntawileh.
- I checked every chekbox in oauth login for permissions. 
- Here is the response of query. (Method: people.get). I think the response is successful.

{
  "resourceName": "people/116199907237833642413",
  "etag": "%EggBAgkKLjc9PhoEAQIFByIMbWhoNTF0MGxndmc9",
  "names": [
    {
      "metadata": {
        "primary": true,
        "source": {
          "type": "PROFILE",
          "id": "116199907237833642413"
        },
        "sourcePrimary": true
      },
      "displayName": "Jaeseong Park",
      "familyName": "Park",
      "givenName": "Jaeseong",
      "displayNameLastFirst": "Park, Jaeseong",
      "unstructuredName": "Jaeseong Park"
    }
  ],
  "emailAddresses": [
    {
      "metadata": {
        "primary": true,
        "verified": true,
        "source": {
          "type": "ACCOUNT",
          "id": "116199907237833642413"
        },
        "sourcePrimary": true
      },
      "value": "jaeseong@gmail.com"
    }
  ]
}

**Comment by ntawileh** [comment] 2022-06-26 18:00
yeah so I would take a look at the google client you created again.  seems like it is not allowed to fetch some sensitive scopes yet?
have you set the status of your client as 'Testing' and added your gmail account as a tester?

![Screen Shot 2022-06-26 at 10 58 55 AM](https://user-images.githubusercontent.com/5069918/175827656-9171d6c8-24d5-4a62-867f-e4ab0f714b62.png)

![Screen Shot 2022-06-26 at 10 59 22 AM](https://user-images.githubusercontent.com/5069918/175827679-78220d68-7331-45d0-8599-8fa9d6c92cc1.png)

**Comment by ParkJaeSeong** [comment] 2022-06-27 03:43
@ntawileh 

In fact, I tested it with all scopes granted. But the result was the same. 
![image](https://user-images.githubusercontent.com/9565700/175851012-b75fc83e-1416-457e-bf0e-913bdcc3283c.png)
![image](https://user-images.githubusercontent.com/9565700/175851036-64088375-faab-48d6-8c7b-fa66d78fafa0.png)

And I added my account as a tester with the publishig status as testing.
![image](https://user-images.githubusercontent.com/9565700/175850925-020529cd-6e07-4515-8139-f37a39750e6f.png)

I think I've tried everything that can be changed in the settings, but I still don't know the cause...

**Comment by ParkJaeSeong** [comment] 2022-06-29 14:37
Thanks for sharing your credentials. I tested it, but the result was the same. There seems to be a problem with my Google Account, but I still don't know.

**Comment by kometenstaub** [comment] 2022-06-30 10:12
I have the same issue.

**Comment by panberbelek** [comment] 2022-07-11 06:25
I think I've the same problem as @ParkJaeSeong - it seems, that google account is not added at all in Obsidian's settings, although an attempt to add an account is successful in the browser ("OK - You can close this tab and go back to Obsidian!" - I named my Google App 'Obsidian').

**Comment by jackli89** [comment] 2022-07-18 17:56
I am also having the same issue. Has anyone found a fix for this yet?

**Comment by BlakeJin** [comment] 2022-07-19 16:27
Same problem as @ParkJaeSeong and @panberbelek. The page shown can close this tab and go back, but actually, no account has been added to the plug-in setting page.  Tried all way, hoping can provide a solution for the issue. Thanks a lot!

**Comment by ntawileh** [comment] 2022-07-19 18:47
could I get one (or more :) ) of you to test this out since the issue isn't reproducible for my google accounts?  if the issue is the same as @ParkJaeSeong, it appears that the call to fetch your own account info does not return an email address.  I've made a small change in the attached build that ignores the unknown email and just assigns a generic name to the account in Settings (i.e. `account#1` `account#2`...etc)
if you want to try this out, please unzip the contents of this file into your .obsidian/plugins/obsidian-google-lookup directory.  after that, you can reload or restart obsidian.
confirm please that you are trying the latest build by checking the version of the plugin and making sure it is `1.2.1` 

[obsidian-google-lookup_1.2.1.zip](https://github.com/ntawileh/obsidian-google-lookup/files/9143840/obsidian-google-lookup_1.2.1.zip)

**Comment by kometenstaub** [comment] 2022-07-19 21:34
![screenshot](https://user-images.githubusercontent.com/83140328/179852115-9ab1db0d-8e50-4735-8d66-a0840c248dd5.png)

Success! It works for me at least with contact info now. I don't use it for Events, so I can't say anything about that.

**Comment by ParkJaeSeong** [comment] 2022-07-21 03:43
Wow! It works! 

![image](https://user-images.githubusercontent.com/9565700/180125143-f4562a60-d295-4448-8005-7738c465724d.png)

My events and addresses have been successfully fetched. Thanks for great plugin!

**Comment by ntawileh** [comment] 2022-07-22 17:48
nice thank you both for testing.  will make a release with this fix

**Closed** 2022-07-22 17:50 UTC
